version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  cooldown:
    default-days: 4
  open-pull-requests-limit: 10
  groups:
    sanity:
      patterns:
        - "@sanity/*"
        - "sanity"
        - "groq"
    dev-dependencies:
      patterns:
        - "@eslint/eslintrc"
        - "@eslint/js"
        - "@sanity/eslint-config-studio"
        - "@typescript-eslint/eslint-plugin"
        - "@typescript-eslint/parser"
        - "eslint"
        - "eslint-config-prettier"
        - "eslint-plugin-prettier"
        - "husky"
        - "lint-staged"
        - "prettier"
    minor-and-patch-dependencies:
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  cooldown:
    default-days: 4
  open-pull-requests-limit: 10
  groups:
    workflows:
      patterns:
        - "*"