export enum DokumentNavn {
  DOKUMENT = 'dokument',
  TITTEL_BOKMAAL = 'tittelBokmaal',
  TITTEL_NYNORSK = 'tittelNynorsk',
  DELMAL_REFERANSE = 'delmalReferanse',
  DELMAL = 'delmal',
  SKAL_ALLTID_MED = 'skalAlltidMed',
  VISNINGSNAVN = 'visningsnavn',
  API_NAVN = 'apiNavn',
  FLETTEFELT = 'flettefelt',
  FLETTEFELT_REFERANSE = 'flettefeltReferanse',
  HTMLFELT = 'htmlfelt',
  HTMLFELT_REFERANSE = 'htmlfeltReferanse',
  LENKE = 'lenke',
  MAPPE = 'mappe',
  GRUPPE_VISNINGSNAVN = 'gruppeVisningsnavn',
  AVANSERT_DELMAL = 'avansertDelmal',
  BOKMAAL = 'bokmaal',
  NYNORSK = 'nynorsk',
  DELMAL_BLOCK = 'delmalBlock',
  VALG_BLOCK = 'valgBlock',
  ER_GJENTAGENDE = 'erGjentagende',
  DOKUMENTMAL = 'dokumentmal',
  VALGFELT = 'valgfelt',
  ER_LISTE = 'erListe',
  ER_FRITEKSTFELT = 'erFritektsfelt',
  FELT = 'felt',
  FELT_VISNINGSNAVN = 'feltVisningsnavn',
  VALG = 'valg',
  VALG_REFERANSE = 'valgReferanse',
  VALGMULIGHET = 'valgmulighet',
  PERIODE = 'periode',
  PERIODER = 'perioder',
  NAVN_I_SYSTEM = 'navnISystem',
  BLOCK = 'block',
  PUBLISERT = 'publisert',
}

export enum SanityTyper {
  STRING = 'string',
  REFERENCE = 'reference',
  BOOLEAN = 'boolean',
  OBJECT = 'object',
  ARRAY = 'array',
  BLOCK = 'block',
  DOCUMENT = 'document',
  TABLE = 'table',
}

export enum BegrunnelseDokumentNavn {
  BEGRUNNELSE = 'begrunnelse',
  BEGRUNNELSE_TYPE = 'begrunnelsetype',
  HJEMLER = 'hjemler',
  EØSHJEMLER = 'eoshjemler',
  HJEMLER_FOLKETRYGDLOVEN = 'hjemlerFolketrygdloven',
  VILKÅR = 'vilkaar',
  ROLLE = 'rolle',
  TRIGGES_AV_LOVLIG_OPPHOLD = 'lovligOppholdTriggere',
  BOSATT_I_RIKET_TRIGGERE = 'bosattIRiketTriggere',
  GIFT_PARTNERSKAP_TRIGGERE = 'giftPartnerskapTriggere',
  BOR_MED_SØKER_TRIGGERE = 'borMedSokerTriggere',
  ØVRIGE_TRIGGERE = 'ovrigeTriggere',
  SKAL_HA_STOR_FORBOSKTAV = 'skalHaStorForbokstav',
  VALGFELT_V2 = 'valgfeltV2',
  ENDRINGSAARSAKER = 'endringsaarsaker',
  ENDRET_UTBETALINGSPERIODE_TRIGGERE = 'endretUtbetalingsperiodeTriggere',
  ENDRET_UTBETALINGSPERIODE_DELT_BOSTED_UTBETALING_TRIGGER = 'endretUtbetalingsperiodeDeltBostedUtbetalingTrigger',
  UTVIDET_BARNETRYGD_TRIGGERE = 'utvidetBarnetrygdTriggere',
  BEHANDLINGSTEMA = 'behandlingstema',
}

export enum EØSBegrunnelseDokumentNavn {
  ANNEN_FORELDERS_AKTIVITET_TRIGGER = 'eosAnnenForeldersAktivitetTrigger',
  BARNETS_BOSTEDSLAND_TRIGGER = 'barnetsBostedslandTrigger',
  KOMPETANSE_TRIGGER = 'kompetanseTrigger',
}
