export enum DokumentNavn {
  DOKUMENT = 'dokument',
  TITTEL_BOKMAAL = 'tittelBokmaal',
  TITTEL_NYNORSK = 'tittelNynorsk',
  DELMAL_REFERANSE = 'delmalReferanse',
  DELMAL = 'delmal',
  SKAL_ALLTID_MED = 'skalAlltidMed',
  VISNINGSNAVN = 'visningsnavn',
  API_NAVN = 'apiNavn',
  FLETTEFELT = 'flettefelt',
  FLETTEFELT_REFERANSE = 'flettefeltReferanse',
  HTMLFELT = 'htmlfelt',
  HTMLFELT_REFERANSE = 'htmlfeltReferanse',
  LENKE = 'lenke',
  MAPPE = 'mappe',
  AVANSERT_DELMAL = 'avansertDelmal',
  BOKMAAL = 'bokmaal',
  NYNORSK = 'nynorsk',
  DELMAL_BLOCK = 'delmalBlock',
  VALG_BLOCK = 'valgBlock',
  ER_GJENTAGENDE = 'erGjentagende',
  DOKUMENTMAL = 'dokumentmal',
  VALGFELT = 'valgfelt',
  ER_LISTE = 'erListe',
  FELT = 'felt',
  FELT_VISNINGSNAVN = 'feltVisningsnavn',
  VALG = 'valg',
  VALG_REFERANSE = 'valgReferanse',
  VALGMULIGHET = 'valgmulighet',
  PERIODE = 'periode',
  PERIODER = 'perioder',
  BEGRUNNELSE = 'begrunnelse',
  BEGRUNNELSE_TYPE = 'Begrunnelsetype',
  HJEMLER = 'hjemler',
  VILKÅR = 'vilkaar',
  FORMULERING = 'formulering',
  FORMULERINGSTYPE = 'formuleringstype',
  NAVN_I_SYSTEM = 'navnISystem',
}

export enum SanityTyper {
  STRING = 'string',
  REFERENCE = 'reference',
  BOOLEAN = 'boolean',
  OBJECT = 'object',
  ARRAY = 'array',
  BLOCK = 'block',
  DOCUMENT = 'document',
  TABLE = 'table',
}
