name: Backup Routine
on:
  pull_request:
  workflow_dispatch:
  schedule:
    # Runs at 04:00 UTC on the 1st and 17th of every month
    - cron: "0 4 */16 * *"
jobs:
  backup-ba-dataset:
    runs-on: ubuntu-18.04
    name: Backup ba dataset
    steps:
      - uses: actions/checkout@v2
      - name: Export ba dataset
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        with:
          args: dataset export ba-brev backups/ba-sak.tar.gz
      - name: Upload ba-sak.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-ba
          path: backups/ba-sak.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
      - name: Import ba dataset til ba-test
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
        with:
          args: dataset import backups/ba-sak.tar.gz ba-test --replace
  backup-ef-dataset:
    runs-on: ubuntu-18.04
    name: Backup ef dataset
    steps:
      - uses: actions/checkout@v2
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        with:
          args: dataset export ef-brev backups/ef-sak.tar.gz
      - name: Upload ef-sak.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-ef
          path: backups/ef-sak.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
      - name: Import ef dataset til ef-test
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
        with:
          args: dataset import backups/ef-sak.tar.gz ef-test --replace