name: CI
on:
  push:
    branches:
      - 'master'
      - 'github-actions-deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 15.x
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy Sanity
        run: |
          set -e
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn sanity deploy