name: Oppdater BA-sak testsett
on:
  workflow_dispatch:

jobs:
  oppdater-ba-testsett:
    runs-on: ubuntu-latest
    name: Oppdater BA-sak testsett
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bruk yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'

      - name: Installer sanity
        run: yarn global add @sanity/cli && sanity install

      - name: Export BA dataset fra Sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        run: sanity dataset export ba-brev backups/ba-sak.tar.gz

      - name: Import BA dataset til ba-test i Sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
        run: sanity dataset import backups/ba-sak.tar.gz ba-test --replace